### ISSUE TITLE
Hi, I wonder if you could provide your model.ckpt?

### ISSUE THREAD

**Issue by rinabell** [itsuki8914/ESRGAN-TensorFlow#2]
I trained this model for a very long time but it failed to provide images like you showed, sometimes it just output an image all dark. I wonder if you could provide your model.ckpt-100000, thank you.

**Comment by itsuki8914** [comment]
I'm sorry for the late reply.
I uploaded a model to googledrive.
https://drive.google.com/drive/folders/1tiK5SuIMBtNGNlDfsko44L62Oyqu8EgK?usp=sharing

I'll Check if there are problems with my implementation.

**Comment by rinabell** [comment]
Tks, and I will commit my debugs tonight LOL
I almost forgot this

**Comment by rinabell** [comment]
I have created the pull request.
